### ISSUE TITLE
Layout problems with new TPU blogs

### ISSUE THREAD

**Issue by huan** [BUPT/bupt.github.io#3]
Please visiting https://bupt.github.io and fix your layout problem. 

@CyFeng16

**Comment by CyFeng16** [comment]
I checked yet but to find the problem may be caused by the website template.
e.g. [bupt.github.io](https://bupt.github.io/tpu/blog/chat-about-tpu-1/) performances differently from [cyfeng.science.io](http://cyfeng.science/tpu/blog/2019/03/07/Chat-about-TPU-1.html) while the same markdown file is used.
Is there some way can I just LINK my original repo with bupt.github.io so that changes/updates/layouts will be the same synchronously.

**Comment by CyFeng16** [comment]
Now you can have a try based on #4 .
Hopes it could work. Also, It auto-updates asynchronously.

**Comment by huan** [comment]
You can run the blog in your local machine by running the following command:

```
make serve
```

You can learn more from README

**Comment by CyFeng16** [comment]
got it! Problem solved! :tada:

**Comment by huan** [comment]
Could please help our repository to add a guide into README about how to confirm the blog post in the local machine before sending a pull request? 

Because that will help other to improve the quality of PR.

**Comment by CyFeng16** [comment]
I thought this problem was solved.

**Comment by huan** [comment]
Great. Please make sure everything in your blog post keeps good, cheers!
